"""Создание таблицы пользователей

Revision ID: 167bd19abc16
Revises: 6020319cf837
Create Date: 2026-07-02 21:25:53.558313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '167bd19abc16'
down_revision: Union[str, Sequence[str], None] = '6020319cf837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_full', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('img_thumbnail', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'img_thumbnail')
    op.drop_column('users', 'img_full')
    # ### end Alembic commands ###
