"""Создание таблицы сотрудников

Revision ID: c1c5f6dc8b84
Revises: 853c70424315
Create Date: 2026-07-02 16:40:40.418393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c5f6dc8b84'
down_revision: Union[str, Sequence[str], None] = '853c70424315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=False))
    op.alter_column('users', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'birthDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
